# Generated by Django 3.2.9 on 2021-11-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20211126_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Évènement', 'verbose_name_plural': 'Évènements'},
        ),
    ]
