# Generated by Django 3.2.9 on 2021-11-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_alter_event_support_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to="crm.client",
            ),
        ),
    ]
