# Generated by Django 3.2.9 on 2021-11-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_alter_contract_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "Annulé"),
                    ("1", "Programmé"),
                    ("2", "En cours de préparation"),
                    ("3", "Terminé"),
                ],
                max_length=30,
            ),
        ),
    ]
