# Generated by Django 3.2.9 on 2021-11-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_auto_20211130_1844"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to="crm.client",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="contract",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract",
                to="crm.contract",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="event",
            unique_together=set(),
        ),
    ]
