# Generated by Django 3.2.9 on 2021-12-06 15:04

import crm.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0016_alter_client_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_manager',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='client_manager', to='accounts.user', validators=[crm.validators.is_sale_validator]),
            preserve_default=False,
        ),
    ]
