# Generated by Django 3.2.9 on 2021-12-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20211210_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='signature_date',
            field=models.DateTimeField(blank=True, verbose_name='date de signature'),
        ),
    ]
