# Generated by Django 3.2.9 on 2021-11-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211122_2002'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('1', 'Gestion'), ('2', 'Vente'), ('3', 'Support')], max_length=30),
        ),
    ]
