# Generated by Django 3.2.9 on 2021-11-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_auto_20211125_1529"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=150,
                unique=True,
                verbose_name="Nom d'utilisateur",
            ),
        ),
    ]
